# Base services for testing/developing with
version: "3.7"

services:
  naturewatch-test:
    build:
      context: .
      target: naturewatch-test
    command: ["sleep", "infinity"]
    volumes:
      - .:/app
    networks:
      - overlay

networks:
  overlay:
